language: java

jdk:
  - oraclejdk7

script: mvn clean package

after_success:
  - upload=$(curl --upload-file ./target/shiro-msativekrb-*-jar-with-dependencies.jar https://transfer.sh/)
  - echo "Build is uploaded here: "$upload
